# Generated by Django 4.0.3 on 2022-04-17 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='users/avatars/default_user_avatar.png', upload_to='users/avatars/', verbose_name='Avatar'),
        ),
    ]
