# Generated by Django 4.0.3 on 2022-05-02 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='cerated_at',
            new_name='created_at',
        ),
    ]
